[2024-06-16T13:46:47.024+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: news_realtime_pipeline.print_hello scheduled__2024-06-15T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
